import { renderToFile } from "@react-pdf/renderer";
import PacketPdf from "../src/pdf/PacketPdf.jsx";
import ALC_CONFIG from "../src/config.js";

const sample = {
  enrollment: {
    startDate: "2026-08-24",
    childFirst: "Maya",
    childMI: "J",
    childLast: "Patel",
    childPreferred: "Maya",
    childGrade: "Pre-K",
    childGender: "Female",
    childDob: "2021-03-14",
    childAddress: "178 Basswood Drive",
    childCity: "Savannah",
    childZip: "31407",
    medicalNotes: "Mild seasonal allergies; inhaler as needed.",
    programs: ["Full Day", "After School"],
    momFirst: "Priya",
    momMI: "A",
    momLast: "Patel",
    momCell: "(912) 555-0144",
    momEmail: "priya.patel@example.com",
    momEmployer: "Memorial Health",
    momOccupation: "Nurse",
    momCustodial: true,
    dadFirst: "Rohan",
    dadMI: "K",
    dadLast: "Patel",
    dadCell: "(912) 555-0198",
    dadEmail: "rohan.patel@example.com",
    dadEmployer: "Gulfstream",
    dadOccupation: "Engineer",
    dadCustodial: true,
    ec1Name: "Anita Shah",
    ec1Rel: "Aunt",
    ec1Cell: "(912) 555-0110",
    ec1Home: "(912) 555-0111",
    ec1Work: "(912) 555-0112",
    ec2Name: "David Chen",
    ec2Rel: "Neighbor",
    ec2Cell: "(912) 555-0166",
    careFrom: "7:00 AM",
    careTo: "5:00 PM",
    mealBreakfast: true,
    mealLunch: true,
    mealSnack: true,
    enLocation: "savannah",
  },
  financial: {
    rpName: "Priya Patel",
    rpDl: "GA1234567",
    rpState: "GA",
    rpEmployer: "Memorial Health",
    rpDob: "1988-06-02",
    rpAddress: "178 Basswood Drive",
    rpCityStateZip: "Savannah, GA 31407",
    rpPhone: "(912) 555-0144",
    rpEmail: "priya.patel@example.com",
    finChildName: "Maya J Patel",
    finEnrollDate: "2026-08-24",
    finAgree: true,
    finSignature: "Priya Patel",
    finSignDate: "2026-08-21",
  },
  transport: {
    trSchoolChoice: "Gould Elementary",
    trSchoolAddress: "5111 Crossroad Dr, Savannah, GA",
    trMiles: "3.2",
    trPickupTime: "2:30 PM",
    trArriveTime: "3:00 PM",
    trMon: true,
    trTue: true,
    trWed: true,
    trThu: true,
    trFri: true,
    trStaffAuth: true,
  },
  emergency: {
    emDoctor: "Dr. Elena Ruiz",
    emDoctorPhone: "(912) 555-2200",
    emSpecial: "Asthma action plan on file",
    emAllergies: "Peanuts",
    emMeds: "Albuterol inhaler",
  },
  ies: { iesDownloadAck: true },
  handbook: { hbAgree: true, hbDate: "2026-08-21", hbSignature: "Priya Patel" },
  photo: {
    photoClassroom: true,
    photoFamily: true,
    photoWeb: false,
    photoMarketing: false,
    photoNone: false,
    photoAgree: true,
    photoSignature: "Priya Patel",
    photoDate: "2026-08-21",
  },
};

const loc = ALC_CONFIG.locations.savannah;
const out = "tmp-pdf-preview/packet-preview.pdf";

await renderToFile(<PacketPdf data={sample} location={loc} which="packet" />, out);
console.log("wrote", out);
