export const ALL_FORMS = [
  {
    id: "enrollment",
    num: "01",
    title: "Enrollment Form",
    blurb: "Location, program, child & guardians, care hours",
    titleEs: "Formulario de inscripción",
    blurbEs: "Ubicación, programa, niño y tutores",
    always: true,
  },
  {
    id: "financial",
    num: "02",
    title: "Financial Responsibility & Tuition",
    blurb: "Responsible party and payment agreement",
    titleEs: "Responsabilidad financiera y matrícula",
    blurbEs: "Parte responsable y acuerdo de pago",
    always: true,
  },
  {
    id: "transport",
    num: "03",
    title: "Transportation Agreement",
    blurb: "School bus routes (Pre-K / before-after / summer only)",
    titleEs: "Acuerdo de transporte",
    blurbEs: "Rutas escolares",
    always: false,
    requiresTransport: true,
  },
  {
    id: "emergency",
    num: "04",
    title: "Vehicle Emergency Medical",
    blurb: "Doctor, allergies, and emergency care consent",
    titleEs: "Información médica de emergencia",
    blurbEs: "Médico, alergias y autorización",
    always: false,
    requiresEmergencyMedical: true,
  },
  {
    id: "ies",
    num: "05",
    title: "Meal Benefit Form (IES)",
    blurb: "Download official CACFP form → optional upload in Documents",
    titleEs: "Formulario de comidas (IES)",
    blurbEs: "Descargar formulario oficial CACFP",
    always: true,
  },
  {
    id: "handbook",
    num: "06",
    title: "Parent Handbook",
    blurb: "Policy acknowledgment (DocuSign-ready)",
    titleEs: "Manual de padres",
    blurbEs: "Acuse de políticas",
    always: true,
  },
  {
    id: "photo",
    num: "07",
    title: "Photo / Video Permission",
    blurb: "Required signed permission form",
    titleEs: "Permiso de foto / video",
    blurbEs: "Formulario de permiso firmado",
    always: true,
  },
  {
    id: "uploads",
    num: "08",
    title: "Documents",
    blurb: "SSNs, IDs, birth cert, shots, residency, optional IES & card photos",
    titleEs: "Documentos",
    blurbEs: "SSN, IDs, acta, vacunas, IES",
    always: true,
  },
];

export const I18N = {
  en: {
    demoBanner: "V1 soft launch · Savannah first",
    demoBannerHint: "· go-live target Aug 10, 2026 · no parent login",
    resetDemo: "Reset Packet",
    heroKicker: "Online enrollment · 2026–2027",
    heroLead:
      "No login required. Complete enrollment, tuition, transport, emergency, and meal forms online — then submit the packet to your center.",
    ctaStart: "Start Enrollment Packet",
    ctaSample: "Load Sample Child",
    ctaJump: "Jump to a Form",
    overviewTitle: "What Parents Complete Online",
    overviewLead:
      "Open the link and fill once. Name, address, and contacts carry across all forms. Submit PDFs to the center — no login required.",
    packetEyebrow: "Your Packet",
    packetTitle: "Enrollment Checklist",
    packetLead:
      "Progress saves in this browser. Shared fields autofill after Enrollment. Add a sibling anytime — one packet can cover multiple children.",
    progress: "{n} of {total} complete",
    statusTodo: "Pending",
    backPacket: "← Back to Packet",
    saveComplete: "Save & Mark Complete",
    toastSaved: "Saved — form marked complete",
    toastSample: "Sample family loaded — open any form",
    toastReset: "Packet reset",
    toastSubmitted: "Packet prepared for center email (V1)",
    confirmReset: "Clear all form progress on this device?",
    doneStrong: "Packet Ready for the Center",
    doneText:
      "Download prefilled PDFs below. Center email and DocuSign wiring come next (not auto-sent yet).",
    doneEyebrow: "What Happens Next",
    doneTitle: "You're All Set",
    doneLead:
      "Fill online once → download prefilled PDFs for the front desk. No parent account.",
    emailToCenter: "SENT TO CENTER",
    emailAttachments: "ATTACHMENTS",
    emailAttachmentList: "Download prefilled PDFs (not auto-emailed yet)",
    reviewChecklist: "Review Checklist",
    printPreview: "Print Webpage",
    enrollmentTitle: "Enrollment Form",
    enrollmentLead: "Child, parent/guardian, emergency contacts, and care schedule.",
    financialTitle: "Financial Responsibility & Tuition Agreement",
    financialLead: "Acknowledge responsibility for tuition, fees, and payment terms.",
    transportTitle: "Transportation Agreement",
    transportLead: "Authorize Angel Learning Center staff to transport your child from school.",
    emergencyTitle: "Vehicle Emergency Medical Information",
    emergencyLead: "Contacts, doctor, allergies, and emergency medical authorization.",
    iesTitle: "Meal Benefit Form (IES)",
    iesLead: "Required each year for the CACFP Food Program.",
    firstName: "First Name",
    lastName: "Last Name",
    preferredName: "Preferred Name",
    gradeClass: "Grade / Class",
    startDate: "Start Date",
    dob: "Date of Birth",
    gender: "Gender",
    childSsn: "Child's SSN",
    address: "Home Address",
    city: "City",
    medicalNotes: "Medical conditions, medications, or special attention",
    motherGuardian: "Mother / Guardian",
    fatherGuardian: "Father / Guardian",
    cellPhone: "Cell Phone",
    email: "Email",
    employer: "Employer",
    occupation: "Occupation",
    custodial: "Custodial Parent",
    emergencyContacts: "Emergency Contacts",
    pickupHint: "authorized for pickup — ID required",
    contact1: "Contact 1",
    fullName: "Full Name",
    relationship: "Relationship",
    careSchedule: "Care Schedule",
    hoursFrom: "Primary Hours From",
    hoursTo: "To",
    tenHourHint: "Cannot exceed 10 hours per day.",
    tuitionAmount: "Current Tuition Amount",
    form1: "Form 1 of 5",
    form2: "Form 2 of 5",
    form3: "Form 3 of 5",
    form4: "Form 4 of 5",
    form5: "Form 5 of 5 · CACFP 2026–2027",
    nextFinancial: "Next: Tuition Agreement →",
    nextTransport: "Next: Transportation →",
    nextEmergency: "Next: Emergency Form →",
    nextIes: "Next: Meal Benefit Form →",
    finishPacket: "Finish Packet →",
    responsibleParty: "Responsible Party",
    legalName: "Full Legal Name",
    dl: "Driver's License / State ID",
    state: "State",
    cityStateZip: "City / State / ZIP",
    phone: "Phone",
    child: "Child",
    childName: "Child's Name",
    enrollDate: "Enrollment Date",
    agreement: "Agreement",
    finTerms1:
      "I acknowledge that I am legally and financially responsible for payment of all tuition, registration fees, late fees, returned payment fees, activities, and any other charges for my child's enrollment at Angel Learning Center.",
    finTerms2:
      "Failure to pay may result in fees, suspension or termination of services, denial of future enrollment, collections, and civil action in a Georgia court.",
    finAgree:
      "I have read this agreement and voluntarily agree to be personally responsible for all amounts owed.",
    printedName: "Printed Name",
    date: "Date",
    esign: "E-Signature",
    childRoute: "Child & Route",
    alcLocation: "ALC Location",
    selectPickupSchool: "School Bus Pickup",
    pickupSchoolHint:
      "Schools served by ALC routes for the location you selected (from center list).",
    pickupTime: "Pickup Time (School)",
    otherSchool: "Other School (if not listed)",
    arriveAlc: "Arrive at Angel Learning Center",
    transportDays: "Transport Days",
    staffAuth: "Angel Learning staff is authorized to transport my child.",
    schoolDistance: "School Name (Distance)",
    schoolAddress: "School Address",
    miles: "Approx. Miles from Center",
    signature: "Signature",
    parentSignature: "Parent / Guardian Signature",
    parents: "Parents",
    fatherName: "Father's Name",
    motherName: "Mother's Name",
    fatherPhones: "Father Home / Work",
    motherPhones: "Mother Home / Work",
    emergencyMedical: "Emergency & Medical",
    altContact: "Emergency Contact (if parents unreachable)",
    doctor: "Child's Doctor",
    doctorPhone: "Doctor Phone",
    facility: "Default emergency facility (from Parent Handbook — editable)",
    allergies: "Child's Allergies",
    meds: "Current Prescribed Medication",
    specialNeeds: "Special Needs and Conditions",
    authorization: "Authorization",
    emAuthText:
      "In the event of an emergency involving my child, and if Angel Learning Center is unable to reach me, I authorize any necessary emergency medical treatment. I also agree to be fully responsible for all medical expenses.",
    iesPart1: "Part I — Enrolled Children",
    childNameLastFirst: "Child's Name (Last, First, M.I.)",
    caseNumber: "SNAP / TANF / FDPIR Case No. (if applicable)",
    iesPart2: "Part II — Household Income",
    childIncome: "Total Child Income / Frequency",
    hhMember: "Household Member",
    earnings: "Work Earnings",
    otherIncome: "Other Income",
    hhSize: "Total Household Members",
    ssn4: "Last 4 of SSN",
    iesPart3: "Part III — Enrollment / Meals",
    careFrom: "Normally in Care From",
    days: "Days",
    mealsReceived: "Meals Normally Received",
    iesPart4: "Part IV — Certification",
    iesCert: "I certify that all information is true and that all income was reported.",
    childInfo: "Child Information",
  },
  es: {
    demoBanner: "Lanzamiento V1 · Savannah primero",
    demoBannerHint: "· meta 10 ago 2026 · sin login",
    resetDemo: "Reiniciar paquete",
    heroKicker: "Paquete de inscripción · 2026–2027",
    heroLead:
      "No se necesita iniciar sesión. Complete en línea inscripción, matrícula, transporte, emergencia y comidas — y envíe el paquete al centro por correo.",
    ctaStart: "Comenzar paquete de inscripción",
    ctaSample: "Cargar niño de ejemplo",
    ctaJump: "Ir a un formulario",
    overviewTitle: "Lo que los padres completan en línea",
    overviewLead:
      "Abra el enlace y llene una vez. Nombre, dirección y contactos se copian a todos los formularios. Envíe PDF al centro — sin inicio de sesión.",
    packetEyebrow: "Su paquete",
    packetTitle: "Lista de inscripción",
    packetLead: "El progreso se guarda en este navegador para la demo. Pulse cualquier formulario.",
    progress: "{n} de {total} completados",
    statusDone: "Completo",
    statusTodo: "Pendiente",
    backPacket: "← Volver al paquete",
    saveComplete: "Guardar y marcar completo",
    toastSaved: "Guardado — formulario marcado completo",
    toastSample: "Familia de ejemplo cargada — abra cualquier formulario",
    toastReset: "Demo reiniciada",
    toastSubmitted: "Demo: el paquete se enviaría al centro en PDF",
    confirmReset: "¿Borrar todo el progreso de la demo en este dispositivo?",
    doneStrong: "Paquete enviado por correo al centro",
    doneText:
      "No se requiere inicio de sesión. Sus formularios se envían en PDF a Angel Learning Center; también puede recibir una copia.",
    doneEyebrow: "Qué sigue",
    doneTitle: "Todo listo",
    doneLead:
      "Llene en línea una vez → enviamos el paquete a recepción. Sin cuenta de padre ni contraseña.",
    emailToCenter: "ENVIADO AL CENTRO",
    emailAttachments: "ADJUNTOS",
    emailAttachmentList: "5 formularios PDF prefllenados",
    reviewChecklist: "Revisar lista",
    printPreview: "Imprimir / vista PDF",
    enrollmentTitle: "Formulario de inscripción",
    enrollmentLead: "Niño, padres/tutores, contactos de emergencia y horario de cuidado.",
    financialTitle: "Responsabilidad financiera y acuerdo de matrícula",
    financialLead: "Reconozca la responsabilidad de matrícula, cuotas y términos de pago.",
    transportTitle: "Acuerdo de transporte",
    transportLead: "Autorice al personal a transportar a su hijo desde la escuela.",
    emergencyTitle: "Información médica de emergencia del vehículo",
    emergencyLead: "Contactos, médico, alergias y autorización médica de emergencia.",
    iesTitle: "Declaración de elegibilidad de comidas (IES)",
    iesLead: "Requerido cada año para el Programa de Alimentos CACFP.",
    firstName: "Nombre",
    lastName: "Apellido",
    preferredName: "Nombre preferido",
    gradeClass: "Grado / clase",
    startDate: "Fecha de inicio",
    dob: "Fecha de nacimiento",
    gender: "Género",
    childSsn: "SSN del niño",
    address: "Dirección",
    city: "Ciudad",
    medicalNotes: "Condiciones médicas, medicamentos o atención especial",
    motherGuardian: "Madre / tutora",
    fatherGuardian: "Padre / tutor",
    cellPhone: "Celular",
    email: "Correo electrónico",
    employer: "Empleador",
    occupation: "Ocupación",
    custodial: "Padre con custodia",
    emergencyContacts: "Contactos de emergencia",
    pickupHint: "(autorizados para recoger — se requiere ID)",
    contact1: "Contacto 1",
    fullName: "Nombre completo",
    relationship: "Parentesco",
    careSchedule: "Horario de cuidado",
    hoursFrom: "Horario desde",
    hoursTo: "Hasta",
    tenHourHint: "No puede exceder 10 horas al día.",
    tuitionAmount: "Monto actual de matrícula",
    form1: "Formulario 1 de 5",
    form2: "Formulario 2 de 5",
    form3: "Formulario 3 de 5",
    form4: "Formulario 4 de 5",
    form5: "Formulario 5 de 5 · CACFP 2026–2027",
    nextFinancial: "Siguiente: Acuerdo de matrícula →",
    nextTransport: "Siguiente: Transporte →",
    nextEmergency: "Siguiente: Emergencia →",
    nextIes: "Siguiente: Beneficios de comidas →",
    finishPacket: "Terminar paquete →",
    responsibleParty: "Parte responsable",
    legalName: "Nombre legal completo",
    dl: "Licencia / ID estatal",
    state: "Estado",
    cityStateZip: "Ciudad / Estado / ZIP",
    phone: "Teléfono",
    child: "Niño",
    childName: "Nombre del niño",
    enrollDate: "Fecha de inscripción",
    agreement: "Acuerdo",
    finTerms1:
      "Reconozco que soy legal y financieramente responsable del pago de toda matrícula, cuotas de inscripción, cargos por mora, pagos devueltos, actividades y cualquier otro cargo por la inscripción de mi hijo en Angel Learning Center.",
    finTerms2:
      "El incumplimiento de pago puede resultar en cargos, suspensión o terminación de servicios, negativa a futuras inscripciones, cobranzas y acción civil en un tribunal de Georgia.",
    finAgree:
      "He leído este acuerdo y acepto voluntariamente ser personalmente responsable de todos los montos adeudados.",
    printedName: "Nombre en letra de molde",
    date: "Fecha",
    esign: "Firma electrónica",
    childRoute: "Niño y ruta",
    alcLocation: "Ubicación de ALC",
    selectPickupSchool: "Recogida escolar en autobús",
    pickupSchoolHint: "Escuelas de las rutas de ALC para la ubicación seleccionada (lista del centro).",
    pickupTime: "Hora de recogida (escuela)",
    otherSchool: "Otra escuela (si no está en la lista)",
    arriveAlc: "Llegada a Angel Learning Center",
    transportDays: "Días de transporte",
    staffAuth: "El personal de Angel Learning está autorizado a transportar a mi hijo.",
    schoolDistance: "Nombre de la escuela (distancia)",
    schoolAddress: "Dirección de la escuela",
    miles: "Millas aproximadas del centro",
    signature: "Firma",
    parentSignature: "Firma del padre / tutor",
    parents: "Padres",
    fatherName: "Nombre del padre",
    motherName: "Nombre de la madre",
    fatherPhones: "Padre casa / trabajo",
    motherPhones: "Madre casa / trabajo",
    emergencyMedical: "Emergencia y médico",
    altContact: "Contacto de emergencia (si no se puede contactar a los padres)",
    doctor: "Médico del niño",
    doctorPhone: "Teléfono del médico",
    facility: "Centro médico que usa el centro",
    allergies: "Alergias del niño",
    meds: "Medicamentos recetados actuales",
    specialNeeds: "Necesidades y condiciones especiales",
    authorization: "Autorización",
    emAuthText:
      "En caso de una emergencia con mi hijo, y si Angel Learning Center no puede comunicarse conmigo, autorizo cualquier atención médica de emergencia necesaria. También acepto ser totalmente responsable de todos los gastos médicos.",
    iesPart1: "Parte I — Niños inscritos",
    childNameLastFirst: "Nombre del niño (Apellido, Nombre, M.I.)",
    caseNumber: "Núm. de caso SNAP / TANF / FDPIR (si aplica)",
    iesPart2: "Parte II — Ingresos del hogar",
    childIncome: "Ingreso total de niños / frecuencia",
    hhMember: "Miembro del hogar",
    earnings: "Ganancias del trabajo",
    otherIncome: "Otros ingresos",
    hhSize: "Total de miembros del hogar",
    ssn4: "Últimos 4 del SSN",
    iesPart3: "Parte III — Inscripción / comidas",
    careFrom: "Normalmente en cuidado desde",
    days: "Días",
    mealsReceived: "Comidas que normalmente recibe",
    iesPart4: "Parte IV — Certificación",
    iesCert: "Certifico que toda la información es verdadera y que se reportaron todos los ingresos.",
    childInfo: "Información del niño",
  },
};

export const SAMPLE = {
  enrollment: {
    enLocation: "savannah",
    programs: ["after_care", "prek"],
    childFirst: "Maya",
    childMI: "J",
    childLast: "Rivera",
    childPreferred: "Maya",
    childGrade: "Afterschool · K",
    startDate: "2026-08-10",
    childDob: "2019-03-14",
    childGender: "Female",
    childAddress: "412 Magnolia Lane",
    childCity: "Savannah",
    childZip: "31407",
    medicalNotes: "Mild peanut allergy — EpiPen in backpack",
    momFirst: "Sofia",
    momMI: "A",
    momLast: "Rivera",
    momCell: "(912) 555-0148",
    momEmail: "sofia.rivera@email.com",
    momEmployer: "Memorial Health",
    momOccupation: "Nurse",
    momCustodial: true,
    dadFirst: "Luis",
    dadMI: "M",
    dadLast: "Rivera",
    dadCell: "(912) 555-0192",
    dadEmail: "luis.rivera@email.com",
    dadEmployer: "Gulfstream Aerospace",
    dadOccupation: "Technician",
    dadCustodial: true,
    ec1Name: "Ana Morales",
    ec1Home: "(912) 555-0177",
    ec1Work: "(912) 555-0178",
    ec1Cell: "(912) 555-0179",
    ec1Rel: "Aunt",
    ec2Name: "Carlos Vega",
    ec2Home: "(912) 555-0180",
    ec2Work: "",
    ec2Cell: "(912) 555-0181",
    ec2Rel: "Family friend",
    careFrom: "07:00",
    careTo: "17:00",
    mealBreakfast: true,
    mealLunch: true,
    mealSnack: true,
  },
  financial: {
    rpName: "Sofia A. Rivera",
    rpDob: "1990-06-02",
    rpDl: "GA-0582914",
    rpState: "GA",
    rpAddress: "412 Magnolia Lane",
    rpCityStateZip: "Savannah, GA 31407",
    rpPhone: "(912) 555-0148",
    rpEmail: "sofia.rivera@email.com",
    rpEmployer: "Memorial Health",
    rp2Name: "",
    finChildName: "Maya J. Rivera",
    finEnrollDate: "2026-08-10",
    finAgree: true,
    finPrintName: "Sofia A. Rivera",
    finSignDate: "2026-07-31",
    finSignature: "Sofia A. Rivera",
  },
  transport: {
    trLocation: "savannah",
    trChild: "Maya J. Rivera",
    trSchoolChoice: "godley",
    trPickupTime: "14:45",
    trArriveTime: "15:15",
    trMon: true,
    trTue: true,
    trWed: true,
    trThu: true,
    trFri: true,
    trStaffAuth: true,
    trSchoolAddress: "2135 Benton Blvd, Savannah, GA 31407",
    trMiles: "4.2",
    trSignature: "Sofia A. Rivera",
    trDate: "2026-07-31",
  },
  emergency: {
    emChild: "Maya J. Rivera",
    emDob: "2019-03-14",
    emAddress: "412 Magnolia Lane, Savannah, GA 31407",
    emFather: "Luis M. Rivera",
    emMother: "Sofia A. Rivera",
    emFatherCell: "(912) 555-0192",
    emMotherCell: "(912) 555-0148",
    emAltName: "Ana Morales",
    emAltPhone: "(912) 555-0179",
    emDoctor: "Dr. Elena Brooks",
    emDoctorPhone: "(912) 555-4410",
    emFacility: "",
    emAllergies: "Peanuts",
    emMeds: "Epinephrine auto-injector as needed",
    emSpecial: "None",
    emAuthChild: "Maya J. Rivera",
    emDate: "2026-07-31",
    emSignature: "Sofia A. Rivera",
  },
  ies: {
    iesDownloadAck: true,
    iesAckPrint: "Sofia A. Rivera",
    iesAckDate: "2026-07-31",
  },
  handbook: {
    hbAgree: true,
    hbPrint: "Sofia A. Rivera",
    hbDate: "2026-07-31",
    hbSignature: "Sofia A. Rivera",
    hbChild: "Maya J. Rivera",
  },
  photo: {
    photoClassroom: true,
    photoFamily: true,
    photoWeb: false,
    photoMarketing: false,
    photoNone: false,
    photoChild: "Maya J. Rivera",
    photoAgree: true,
    photoPrint: "Sofia A. Rivera",
    photoDate: "2026-07-31",
    photoSignature: "Sofia A. Rivera",
    permWaterSprinkler: false,
    permWaterSplashing: false,
    permWaterPools: false,
    permWaterTable: false,
    prepBabyWipes: false,
    prepBandAids: false,
    prepNeosporin: false,
    prepBactine: false,
    prepSunscreen: false,
    prepInsectRepellent: false,
    prepNonRxOintment: false,
    prepBabyPowder: false,
    prepOther: "",
  },
  uploads: {
    upConfirm: true,
    files: {
      parent_ssn_doc: [
        { name: "sofia-ssn.pdf", size: 120000, type: "application/pdf", uploadedAt: "2026-07-31T12:00:00.000Z", uploadedBy: "parent" },
      ],
      child_ssn_doc: [
        { name: "maya-ssn.pdf", size: 110000, type: "application/pdf", uploadedAt: "2026-07-31T12:00:00.000Z", uploadedBy: "parent" },
      ],
      birth_cert: [
        { name: "maya-birth-cert.pdf", size: 200000, type: "application/pdf", uploadedAt: "2026-07-31T12:00:00.000Z", uploadedBy: "parent" },
      ],
      ga_shot_records: [
        { name: "maya-3231.pdf", size: 180000, type: "application/pdf", uploadedAt: "2026-07-31T12:00:00.000Z", uploadedBy: "parent" },
      ],
      ga_residency: [
        { name: "utility-bill-ga.pdf", size: 90000, type: "application/pdf", uploadedAt: "2026-07-31T12:00:00.000Z", uploadedBy: "parent" },
      ],
      ga_parent_ids: [
        { name: "sofia-dl.pdf", size: 95000, type: "application/pdf", uploadedAt: "2026-07-31T12:00:00.000Z", uploadedBy: "parent" },
      ],
      completed_ies: [
        { name: "ies-completed.pdf", size: 150000, type: "application/pdf", uploadedAt: "2026-07-31T12:00:00.000Z", uploadedBy: "parent" },
      ],
    },
    staffLog: [],
  },
};
